<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="../css/login.css">
  <title></title>
</head>
<body>
  <header>
    <h1><span>C</span>reative</h1>
    <div class="links">
      <p>New User?</p>
      <a href="">Sign Up</a>
    </div>
  </header>
  <main>  
      <img src="../images/img.svg" alt="">
      <div class="forms">
        <div class="titles">
          <h1>Welcome Back!</h1>
          <p>Login to continue</p>
        </div>
        <div class="inputs">
          <input type="email" placeholder="username111@gmail.com">
          <input type="password" placeholder="Enter password">
        </div>
        <div class="buttons">
          <button>Login</button>
          <a href="">Forget Password</a>
        </div>
      </div>
  </main>
</body>
</html>
